config/routes.rb
Rails.application.routes.draw do

  # get 'applications/index'
  # get 'applications/new'
  # get 'applications/create'
  devise_for :users
  root to: 'positions#index'
  # root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #crud actions:
  resources :recruiters, only: [:index, :new, :create]

  resources :positions
  resources :candidates do
    resources :applications
  end
end

app/models/position.rb
class Position < ApplicationRecord
  serialize :top_recruiters
  belongs_to :user, optional: true
  has_many :applications, dependent: :destroy
  has_many :candidates, through: :applications
  has_many :position_skills, dependent: :destroy
  has_many :skills, through: :position_skills
  has_many :scorecards
  validates :title, presence: true
  validates :company, presence: true

  # attr_accessor :title

  # def to_label
  #   "#{title}"
  # end

  STATUSES = ["junior", "mid", "senior"]
  validates :seniority, inclusion: { in: STATUSES }
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  def index
    @positions = Position.all
  end

  def show
    @position = Position.find(params[:id])
  end

  def new
    @position = Position.new
  end

  def create
    @recruiters = Recruiter.all
    @position = Position.new(position_params)
    top_recruiters(@position)
    @position.save
    redirect_to positions_path
  end

  def destroy
    @position = Position.find(params[:id])
    @position.destroy!
    respond_to do |format|
      format.html { redirect_to positions_path }
      format.js
    end
  end

  private

  def position_params
    params.require(:position).permit(:title, :company, :top_recruiters, :seniority, :skill_ids => [])
  end

  def skills_recruiters_position(position)
    @recruiters.each do |recruiter|
      recruiter.skills_match[position.title] = (recruiter.skills & position.skills).length
      recruiter.save
    end
  end

  def seniority_recruiters_position(position)
    @recruiters.select do |recruiter|
      case position.seniority
      when 'senior'
        recruiter.seniority == 'senior'
      else
        recruiter.seniority == 'senior' || recruiter.seniority == 'mid'
      end
    end
  end

  def top_recruiters(position)
    skills_recruiters_position(position)
    recruiters_array = seniority_recruiters_position(position).reject do |recruiter|
      recruiter.skills_match[position.title].to_i == 0
    end
    position.top_recruiters << recruiters_array.sort_by { |recruiter| recruiter.skills_match[position.title] }.reverse!.first(3)
    position.top_recruiters.flatten!
  end
end

app/views/positions/index.html.erb
<h3>All positions</h3>
<div class="positions-titles">
  <div class="container">
    <div class="row justify-content-between">
      <% @positions.each do |position| %>
        <div class="col-4">
          <%= link_to position_path(position) do %>
            <p><%= position.seniority %> <%= position.title %></p>
          <% end %>
        </div>
        <div class="col-4">
          <p><% position.skills.each do |skill| %>
            #<%= skill.name %>
          <% end %></p>
        </div>
        <div class="col-4">
          <p>
            <a data-toggle="collapse" href="#collapseExample<%= position.id %>" role="button" aria-expanded="false" aria-controls="collapseExample">
              <%= position.applications.count %> <%= position.applications.count == 1 ? 'applicant' : 'applicants' %>
            </a>
          </p>
          <div class="collapse" id="collapseExample<%= position.id %>">
            <div class="card card-body">
              <% position.applications.each do |application| %>
                <%= link_to candidate_path(application.candidate) do %>
                  <%= application.candidate.first_name %> <%= application.candidate.last_name %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= link_to "+ New position", new_position_path, class: "btn btn-primary"%>

app/views/positions/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="form-position justify-content-center">
        <h1>Add a job position:</h1>
        <%= simple_form_for(@position) do |p| %>
        <div class="row">
          <div class="col-6">
            <%= p.input :title, placeholder: "Enter position's title" %>
          </div>
          <div class="col-6">
            <%= p.input :company, placeholder: "Enter company's name" %>
          </div>
        </div>
        <div class="form-group">
          <label class="control-label check_boxes optional">Skills</label>
          <input type="hidden" name="position[skill_ids][]" value="">
          <div class="skill-choices">
            <% Skill.all.each do |skill| %>
            <input class="hidden" type="checkbox" value="<%= skill.id %>" name="position[skill_ids][]" id="position_skill_ids_<%= skill.id %>">
            <label class="skill-choice" for="position_skill_ids_<%= skill.id %>">
              <%= skill.name %>
            </label>
            <% end %>
          </div>
        </div>
        <%= p.input :seniority, collection: Position::STATUSES, prompt: "Select" %>
        <%= p.submit "Save", class: "btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/positions/show.html.erb
<h3><%= @position.seniority %> <%= @position.title %></h3>
<p>position at: <%= @position.company %></p>
<p><% @position.skills.each do |skill| %>
  #<%= skill.name %>
<% end %></p>
<p><%= link_to "Delete position", position_path(@position), method: :delete, data: {confirm: "Deleting the position. Are you sure?"} %></p>
<p><%= link_to "All positions", positions_path %></p>