config/routes.rb
Rails.application.routes.draw do

  # get 'applications/index'
  # get 'applications/new'
  # get 'applications/create'
  devise_for :users
  root to: 'positions#index'
  # root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #crud actions:
  resources :recruiters, only: [:index, :new, :create]

  resources :positions
  resources :candidates do
    resources :applications
  end
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  has_many :applications, dependent: :destroy
  has_many :positions, through: :applications
  has_many :scorecards, through: :applications
  has_many :candidate_skills, dependent: :destroy
  has_many :skills, through: :candidate_skills
  has_many :appointments

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true

  STATUSES = ["junior", "mid", "senior"]
  validates :seniority, inclusion: { in: STATUSES }
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def index
    @candidates = Candidate.all
  end

  def show
    @candidate = Candidate.find(params[:id])
    @application = Application.new
  end

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidate_params)
    @candidate.save
    redirect_to candidate_path(@candidate)
  end


  private

  def candidate_params
    params.require(:candidate).permit(:first_name, :last_name, :linkedin, :seniority, :email, :skill_ids => [])
  end
end

app/views/candidates/create.html.erb
<h1>Candidates#create</h1>
<p>Find me in app/views/candidates/create.html.erb</p>

app/views/candidates/destroy.html.erb
<h1>Candidates#destroy</h1>
<p>Find me in app/views/candidates/destroy.html.erb</p>

app/views/candidates/edit.html.erb
<h1>Candidates#edit</h1>
<p>Find me in app/views/candidates/edit.html.erb</p>

app/views/candidates/index.html.erb
<table style="width:40%">
  <thead>
    <tr>
      <th>Candidate</th>
      <th>Positions applied</th>
    </tr>
  </thead>
  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td>
          <%= link_to candidate_path(candidate) do %>
            <p><%= candidate.first_name %> <%= candidate.last_name %></p>
          <% end %>
        </td>
        <td>
          <% candidate.applications.each do |application| %>
            <p><%= link_to position_path(application.position) do %>
              <%= application.position.title %>
            <% end %></p>
          <% end %>
        </td>
        <td>
          <%= link_to candidate_applications_path(candidate) do %>
            <p>Go to open applications</p>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to "+ New candidate", new_candidate_path, class: "btn btn-primary"%>

app/views/candidates/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="form-position justify-content-center">
        <h1>New Applicant</h1>
        <%= simple_form_for(@candidate) do |p| %>
        <div class="row">
          <div class="col-6">
            <%= p.input :first_name, placeholder: "Jane" %>
          </div>
          <div class="col-6">
            <%= p.input :last_name, placeholder: "Smith" %>
          </div>
          <div class="col-6">
            <%= p.input :email, placeholder: "smith@mail.com" %>
          </div>
          <div class="col-6">
            <%= p.input :linkedin, placeholder: "www.linkedin.com/jsmith" %>
          </div>
        </div>
        <div class="form-group">
          <label class="control-label check_boxes optional">Assign skills</label>
          <input type="hidden" name="candidate[skill_ids][]" value="">
          <div class="skill-choices">
            <% Skill.all.each do |skill| %>
            <input class="hidden" type="checkbox" value="<%= skill.id %>" name="candidate[skill_ids][]" id="candidate_skill_ids_<%= skill.id %>">
            <label class="skill-choice" for="candidate_skill_ids_<%= skill.id %>">
              <%= skill.name %>
            </label>
            <% end %>
          </div>
        </div>
        <%= p.input :seniority, collection: Candidate::STATUSES, prompt: "Select" %>

        <%= p.submit "Create a candidate", class: "btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/candidates/show.html.erb
<h3><%= @candidate.first_name %> <%= @candidate.last_name %></h3>
<p>email: <%= @candidate.email %></p>
<p>LinkedIn: <%= @candidate.linkedin %></p>
<p>Skills:<% @candidate.skills.each do |skill| %>
  #<%= skill.name %>
<% end %></p>

<%= simple_form_for([@candidate, @application]) do |p| %>
  <% if @application.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @application.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= p.association :position, :include_blank => false, :label_method => lambda { |position| "#{position.title}" }, prompt: "Select" %>
  <%= p.submit %>
<% end %>
<p><%= link_to "Back to all applicants", candidates_path %></p>

app/views/candidates/update.html.erb
<h1>Candidates#update</h1>
<p>Find me in app/views/candidates/update.html.erb</p>