config/routes.rb
Rails.application.routes.draw do

  # get 'applications/index'
  # get 'applications/new'
  # get 'applications/create'
  devise_for :users
  root to: 'positions#index'
  # root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #crud actions:
  resources :recruiters, only: [:index, :new, :create]

  resources :positions
  resources :candidates do
    resources :applications
  end
end

app/models/recruiter.rb
class Recruiter < ApplicationRecord
  store_accessor :skills_match
  # serialize :skills_match, Hash
  has_many :applications
  has_many :appointments
  # has_many :candidates, through: :applications
  # has_many :positions, through: :applications
  has_many :recruiter_skills, dependent: :destroy
  has_many :skills, through: :recruiter_skills

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :seniority, presence: true


  STATUSES = ["junior", "mid", "senior"]
  validates :seniority, inclusion: { in: STATUSES }
end

app/controllers/recruiters_controller.rb
class RecruitersController < ApplicationController
  def index
    @recruiters = Recruiter.all
  end

  def new
    @recruiter = Recruiter.new
  end

  def create
    @recruiter = Recruiter.new(recruiter_params)
    render :new and return unless @recruiter.save
    # if @recruiter.save
    #   next
    # else
    #   render :new and return
    # end

    redirect_to recruiters_path
  end

  private

  def recruiter_params
    params.require(:recruiter).permit(:first_name, :last_name, :seniority, :email, :skill_ids => [])
  end
end

app/views/recruiters/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4>All employees available for recruitment of new candidates</h4>
  </div>
  <div class="row justify-content-center">
    <table style="width:60%">
      <thead>
        <tr>
          <th>Employee</th>
          <th>Skills</th>
          <th>Seniority</th>
        </tr>
      </thead>
      <tbody>
        <% @recruiters.each do |recruiter| %>
          <tr>
            <td>
              <p><%= recruiter.first_name %> <%= recruiter.last_name %></p>
            </td>
            <td>
              <% recruiter.skills.each do |skill| %>
                <p>#<%= skill.name %>
              <% end %></p>
            </td>
            <td>
              <p><%= recruiter.seniority %></p>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= link_to "+ New recruiter", new_recruiter_path, class: "btn btn-primary"%>

app/views/recruiters/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="form-position justify-content-center">
        <h1>New Recruiter/Employee</h1>
        <%= simple_form_for(@recruiter) do |p| %>
        <div class="row">
          <div class="col-6">
            <%= p.input :first_name, placeholder: "David" %>
          </div>
          <div class="col-6">
            <%= p.input :last_name, placeholder: "Sellam" %>
          </div>
          <div class="col-6">
            <%= p.input :email, placeholder: "sellam@mail.com" %>
          </div>
        </div>
        <div class="form-group">
          <label class="control-label check_boxes optional">Assign skills</label>
          <input type="hidden" name="recruiter[skill_ids][]" value="">
          <div class="skill-choices">
            <% Skill.all.each do |skill| %>
            <input class="hidden" type="checkbox" value="<%= skill.id %>" name="recruiter[skill_ids][]" id="recruiter_skill_ids_<%= skill.id %>">
            <label class="skill-choice" for="recruiter_skill_ids_<%= skill.id %>">
              <%= skill.name %>
            </label>
            <% end %>
          </div>
        </div>
        <%= p.input :seniority, collection: Recruiter::STATUSES, prompt: "Select seniority level" %>

        <%= p.submit "Create a recruiter", class: "btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>